### ISSUE TITLE
craig test

### ISSUE THREAD

**Issue by crigdongov** [bcgov/ocio-enterprise-architecture#78]
test test

**Comment by DAJonas** [comment]
Successful if this was your intention 😊

--
Denise Jonas | Manager, Digital Investment Office
Secretariat, Finance & Operations  | Digital Investment Office | Office of the Chief Information Officer | Ministry of Citizens’ Services
250 516-0462 | ***@***.******@***.***>


From: Craig Rigdon ***@***.***>
Sent: Tuesday, September 5, 2023 10:14 AM
To: bcgov/ocio-enterprise-architecture ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bcgov/ocio-enterprise-architecture] craig test (Issue #78)

[EXTERNAL] This email came from an external source. Only open attachments or links that you are expecting from a known sender.


test test
